// Auto-Generated by FAKE; do not edit
// <auto-generated/>
using System.Reflection;

[assembly: AssemblyTitle("ParserTestsWithNet48")]
[assembly: AssemblyProduct("NpgsqlFSharpAnalyzer")]
[assembly: AssemblyVersion("3.12.0")]
[assembly: AssemblyMetadata("ReleaseDate","2020-08-29T00:00:00.0000000")]
[assembly: AssemblyFileVersion("3.12.0")]
[assembly: AssemblyInformationalVersion("3.12.0")]
[assembly: AssemblyMetadata("ReleaseChannel","release")]
[assembly: AssemblyMetadata("GitHash","fdb4e9da4d035afc38f1941a84adf621fd8c2574")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const System.String AssemblyTitle = "ParserTestsWithNet48";
        internal const System.String AssemblyProduct = "NpgsqlFSharpAnalyzer";
        internal const System.String AssemblyVersion = "3.12.0";
        internal const System.String AssemblyMetadata_ReleaseDate = "2020-08-29T00:00:00.0000000";
        internal const System.String AssemblyFileVersion = "3.12.0";
        internal const System.String AssemblyInformationalVersion = "3.12.0";
        internal const System.String AssemblyMetadata_ReleaseChannel = "release";
        internal const System.String AssemblyMetadata_GitHash = "fdb4e9da4d035afc38f1941a84adf621fd8c2574";
    }
}
