// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("Ubik")>]
[<assembly: AssemblyProductAttribute("NpgsqlFSharpAnalyzer")>]
[<assembly: AssemblyVersionAttribute("3.26.0")>]
[<assembly: AssemblyMetadataAttribute("ReleaseDate","2021-05-06T00:00:00.0000000")>]
[<assembly: AssemblyFileVersionAttribute("3.26.0")>]
[<assembly: AssemblyInformationalVersionAttribute("3.26.0")>]
[<assembly: AssemblyMetadataAttribute("ReleaseChannel","release")>]
[<assembly: AssemblyMetadataAttribute("GitHash","89f1b78fc64964e3bc01f0738f8780c3f12099ae")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "Ubik"
    let [<Literal>] AssemblyProduct = "NpgsqlFSharpAnalyzer"
    let [<Literal>] AssemblyVersion = "3.26.0"
    let [<Literal>] AssemblyMetadata_ReleaseDate = "2021-05-06T00:00:00.0000000"
    let [<Literal>] AssemblyFileVersion = "3.26.0"
    let [<Literal>] AssemblyInformationalVersion = "3.26.0"
    let [<Literal>] AssemblyMetadata_ReleaseChannel = "release"
    let [<Literal>] AssemblyMetadata_GitHash = "89f1b78fc64964e3bc01f0738f8780c3f12099ae"
