// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("NpgsqlFSharpAnalyzer.Tests")>]
[<assembly: AssemblyProductAttribute("NpgsqlFSharpAnalyzer")>]
[<assembly: AssemblyVersionAttribute("1.3.0")>]
[<assembly: AssemblyMetadataAttribute("ReleaseDate","2020-02-18T00:00:00.0000000")>]
[<assembly: AssemblyFileVersionAttribute("1.3.0")>]
[<assembly: AssemblyInformationalVersionAttribute("1.3.0")>]
[<assembly: AssemblyMetadataAttribute("ReleaseChannel","release")>]
[<assembly: AssemblyMetadataAttribute("GitHash","ebf94c529273dd88cfd59bffd4b4d75849a5c310")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "NpgsqlFSharpAnalyzer.Tests"
    let [<Literal>] AssemblyProduct = "NpgsqlFSharpAnalyzer"
    let [<Literal>] AssemblyVersion = "1.3.0"
    let [<Literal>] AssemblyMetadata_ReleaseDate = "2020-02-18T00:00:00.0000000"
    let [<Literal>] AssemblyFileVersion = "1.3.0"
    let [<Literal>] AssemblyInformationalVersion = "1.3.0"
    let [<Literal>] AssemblyMetadata_ReleaseChannel = "release"
    let [<Literal>] AssemblyMetadata_GitHash = "ebf94c529273dd88cfd59bffd4b4d75849a5c310"
