// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("FParsec")>]
[<assembly: AssemblyProductAttribute("NpgsqlFSharpAnalyzer")>]
[<assembly: AssemblyVersionAttribute("3.13.0")>]
[<assembly: AssemblyMetadataAttribute("ReleaseDate","2020-09-04T00:00:00.0000000")>]
[<assembly: AssemblyFileVersionAttribute("3.13.0")>]
[<assembly: AssemblyInformationalVersionAttribute("3.13.0")>]
[<assembly: AssemblyMetadataAttribute("ReleaseChannel","release")>]
[<assembly: AssemblyMetadataAttribute("GitHash","8510b403b2b0a20a3207cc5c7637d8406f2aaee5")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "FParsec"
    let [<Literal>] AssemblyProduct = "NpgsqlFSharpAnalyzer"
    let [<Literal>] AssemblyVersion = "3.13.0"
    let [<Literal>] AssemblyMetadata_ReleaseDate = "2020-09-04T00:00:00.0000000"
    let [<Literal>] AssemblyFileVersion = "3.13.0"
    let [<Literal>] AssemblyInformationalVersion = "3.13.0"
    let [<Literal>] AssemblyMetadata_ReleaseChannel = "release"
    let [<Literal>] AssemblyMetadata_GitHash = "8510b403b2b0a20a3207cc5c7637d8406f2aaee5"
