// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("FParsec")>]
[<assembly: AssemblyProductAttribute("NpgsqlFSharpAnalyzer")>]
[<assembly: AssemblyVersionAttribute("3.16.0")>]
[<assembly: AssemblyMetadataAttribute("ReleaseDate","2020-09-15T00:00:00.0000000")>]
[<assembly: AssemblyFileVersionAttribute("3.16.0")>]
[<assembly: AssemblyInformationalVersionAttribute("3.16.0")>]
[<assembly: AssemblyMetadataAttribute("ReleaseChannel","release")>]
[<assembly: AssemblyMetadataAttribute("GitHash","9ada11966d9a0a63829dd0976addedf8d6224a15")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "FParsec"
    let [<Literal>] AssemblyProduct = "NpgsqlFSharpAnalyzer"
    let [<Literal>] AssemblyVersion = "3.16.0"
    let [<Literal>] AssemblyMetadata_ReleaseDate = "2020-09-15T00:00:00.0000000"
    let [<Literal>] AssemblyFileVersion = "3.16.0"
    let [<Literal>] AssemblyInformationalVersion = "3.16.0"
    let [<Literal>] AssemblyMetadata_ReleaseChannel = "release"
    let [<Literal>] AssemblyMetadata_GitHash = "9ada11966d9a0a63829dd0976addedf8d6224a15"
