// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("examples")>]
[<assembly: AssemblyProductAttribute("NpgsqlFSharpAnalyzer")>]
[<assembly: AssemblyVersionAttribute("1.4.0")>]
[<assembly: AssemblyMetadataAttribute("ReleaseDate","2020-02-18T00:00:00.0000000")>]
[<assembly: AssemblyFileVersionAttribute("1.4.0")>]
[<assembly: AssemblyInformationalVersionAttribute("1.4.0")>]
[<assembly: AssemblyMetadataAttribute("ReleaseChannel","release")>]
[<assembly: AssemblyMetadataAttribute("GitHash","bb2e1089de264e0f90647420b6f773675d2bcda9")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "examples"
    let [<Literal>] AssemblyProduct = "NpgsqlFSharpAnalyzer"
    let [<Literal>] AssemblyVersion = "1.4.0"
    let [<Literal>] AssemblyMetadata_ReleaseDate = "2020-02-18T00:00:00.0000000"
    let [<Literal>] AssemblyFileVersion = "1.4.0"
    let [<Literal>] AssemblyInformationalVersion = "1.4.0"
    let [<Literal>] AssemblyMetadata_ReleaseChannel = "release"
    let [<Literal>] AssemblyMetadata_GitHash = "bb2e1089de264e0f90647420b6f773675d2bcda9"
