// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("examples")>]
[<assembly: AssemblyProductAttribute("NpgsqlFSharpAnalyzer")>]
[<assembly: AssemblyVersionAttribute("3.21.0")>]
[<assembly: AssemblyMetadataAttribute("ReleaseDate","2020-12-08T00:00:00.0000000")>]
[<assembly: AssemblyFileVersionAttribute("3.21.0")>]
[<assembly: AssemblyInformationalVersionAttribute("3.21.0")>]
[<assembly: AssemblyMetadataAttribute("ReleaseChannel","release")>]
[<assembly: AssemblyMetadataAttribute("GitHash","2d384f746febd40976d8f3f2cc4314f4d0c05681")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "examples"
    let [<Literal>] AssemblyProduct = "NpgsqlFSharpAnalyzer"
    let [<Literal>] AssemblyVersion = "3.21.0"
    let [<Literal>] AssemblyMetadata_ReleaseDate = "2020-12-08T00:00:00.0000000"
    let [<Literal>] AssemblyFileVersion = "3.21.0"
    let [<Literal>] AssemblyInformationalVersion = "3.21.0"
    let [<Literal>] AssemblyMetadata_ReleaseChannel = "release"
    let [<Literal>] AssemblyMetadata_GitHash = "2d384f746febd40976d8f3f2cc4314f4d0c05681"
