// Auto-Generated by FAKE; do not edit
// <auto-generated/>
using System.Reflection;

[assembly: AssemblyTitle("NpgsqlFSharpVs")]
[assembly: AssemblyProduct("NpgsqlFSharpAnalyzer")]
[assembly: AssemblyVersion("3.11.0")]
[assembly: AssemblyMetadata("ReleaseDate","2020-08-18T00:00:00.0000000")]
[assembly: AssemblyFileVersion("3.11.0")]
[assembly: AssemblyInformationalVersion("3.11.0")]
[assembly: AssemblyMetadata("ReleaseChannel","release")]
[assembly: AssemblyMetadata("GitHash","dbe65f09faf4b6ddf40d5e84320acd761f6b4d81")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const System.String AssemblyTitle = "NpgsqlFSharpVs";
        internal const System.String AssemblyProduct = "NpgsqlFSharpAnalyzer";
        internal const System.String AssemblyVersion = "3.11.0";
        internal const System.String AssemblyMetadata_ReleaseDate = "2020-08-18T00:00:00.0000000";
        internal const System.String AssemblyFileVersion = "3.11.0";
        internal const System.String AssemblyInformationalVersion = "3.11.0";
        internal const System.String AssemblyMetadata_ReleaseChannel = "release";
        internal const System.String AssemblyMetadata_GitHash = "dbe65f09faf4b6ddf40d5e84320acd761f6b4d81";
    }
}
