// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("NpgsqlFSharpParser")>]
[<assembly: AssemblyProductAttribute("NpgsqlFSharpAnalyzer")>]
[<assembly: AssemblyVersionAttribute("3.17.0")>]
[<assembly: AssemblyMetadataAttribute("ReleaseDate","2020-09-15T00:00:00.0000000")>]
[<assembly: AssemblyFileVersionAttribute("3.17.0")>]
[<assembly: AssemblyInformationalVersionAttribute("3.17.0")>]
[<assembly: AssemblyMetadataAttribute("ReleaseChannel","release")>]
[<assembly: AssemblyMetadataAttribute("GitHash","985f38c696391f5c8f38f4498e3a59db66ffe3c6")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "NpgsqlFSharpParser"
    let [<Literal>] AssemblyProduct = "NpgsqlFSharpAnalyzer"
    let [<Literal>] AssemblyVersion = "3.17.0"
    let [<Literal>] AssemblyMetadata_ReleaseDate = "2020-09-15T00:00:00.0000000"
    let [<Literal>] AssemblyFileVersion = "3.17.0"
    let [<Literal>] AssemblyInformationalVersion = "3.17.0"
    let [<Literal>] AssemblyMetadata_ReleaseChannel = "release"
    let [<Literal>] AssemblyMetadata_GitHash = "985f38c696391f5c8f38f4498e3a59db66ffe3c6"
